const quote=["My favorite things in life don’t cost any money. It’s really clear that the most precious resource we all have is time.","Have the courage to follow your heart and intuition. They somehow know what you truly want to become.","I think if you do something and it turns out pretty good, then you should go do something else wonderful, not dwell on it for too long. Just figure out what’s next.","Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.","Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it.","Quality is more important than quantity. One home run is much better than two doubles.","That’s been one of my mantras—focus and simplicity. Simple can be harder than complex; you have to work hard to get your thinking clean to make it simple.","Being the richest man in the cemetery doesn’t matter to me. Going to bed at night saying we’ve done something wonderful...that’s what matters to me.","The people who are crazy enough to think they can change the world are the ones who do.","Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma—which is living with the results of other people’s thinking. Don’t let the noise of others’ opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition.","I’m convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance.","The only way to do great work is to love what you do.","The greatest thing is when you do put your heart and soul into something over an extended period of time, and it is worth it.","You can’t connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something — your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.","Don’t let the noise of other’s’ opinions drown out your own inner voice.","Sometimes life hits you in the head with a brick. Don’t lose faith."]
let words=document.getElementById("words");

function change(){
  let hex="#";
  hex+=Math.round((Math.random()*16777215)).toString(16);
  document.body.style.backgroundColor=hex;
  const i=Math.floor((Math.random()*quote.length));
  words.textContent='"'+quote[i]+'"';
}
